#Requires -Version 7.5
[CmdletBinding()]param()
$ErrorActionPreference='Stop';Set-StrictMode -Version 3.0;[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false);$OutputEncoding=[Text.UTF8Encoding]::new($false)
$SourceRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$Pwsh=(Get-Process -Id $PID).Path
$C1a=Join-Path $SourceRoot 'scripts\lib\tablet-layout-c1a.ps1';$Validator=Join-Path $SourceRoot 'scripts\lib\tablet-layout-observation-c1b-v1-validator.ps1';$C1b=Join-Path $SourceRoot 'scripts\lib\tablet-layout-c1b.ps1'
. $C1a;. $Validator;. $C1b
function Check([bool]$Value,[string]$Message){if(-not$Value){throw $Message}}
function Run-Git([string]$At,[string[]]$Arguments){$all=@('-C',$At)+$Arguments;$text=& git @all 2>&1;if($LASTEXITCODE-ne0){throw "git $($Arguments-join' ') failed: $text"};return $text}
function Get-IndependentSha256([byte[]]$Bytes){$hasher=[Security.Cryptography.SHA256]::Create();try{return 'sha256:'+([Convert]::ToHexString($hasher.ComputeHash($Bytes))).ToLowerInvariant()}finally{$hasher.Dispose()}}
function Get-IndependentFileSha256([string]$Path){$bytes=[IO.File]::ReadAllBytes($Path);try{return Get-IndependentSha256 $bytes}finally{if($bytes.Length){[Array]::Clear($bytes,0,$bytes.Length)}}}
function Read-FailureEvidenceStrict([string]$Path){
    $bytes=[IO.File]::ReadAllBytes($Path)
    try{$raw=ConvertFrom-TL1C1aStrictUtf8 $bytes 'C1b E2E failure evidence';$value=ConvertFrom-TL1C1bClosedJson $raw}
    finally{if($bytes.Length){[Array]::Clear($bytes,0,$bytes.Length)}}
    Assert-TL1C1bExactObjectKeys $value @('schema','run_id','status','reason_code','cleanup','runtime_origin_verified','runtime_evidence','layout_accepted','wechat_layout_verified','editor_action_ready','p0_capability','execution_grant') 'failure evidence'
    Check ($value.schema-ceq'tablet-layout-c1b-failure/v1') 'failure evidence schema drift'
    return $value
}
$root=Join-Path ([IO.Path]::GetTempPath()) ('tl1-c1b-e2e-'+[guid]::NewGuid().ToString('N'));$repo=Join-Path $root 'repo';$state=Join-Path $root 'state';$sdk=Join-Path $root 'sdk';[void](New-Item -ItemType Directory -Path $root,$state,(Join-Path $sdk 'build-tools\99.0.0'),(Join-Path $sdk 'platform-tools'))
try{
    $clone=& git clone --shared --quiet $SourceRoot $repo 2>&1;if($LASTEXITCODE-ne0){throw "shared clone failed: $clone"}
    $overlay=@(
      'scripts/run-tablet-layout-c1b.ps1','scripts/lib/tablet-layout-c1b.ps1','scripts/lib/tablet-layout-observation-c1b-v1-validator.ps1',
      'docs/contracts/tablet-layout-c1b-sidecar-v1.schema.json','docs/contracts/tablet-layout-c1b-v1.md','docs/contracts/tablet-layout-observation-c1b-v1.schema.json','docs/contracts/tablet-layout-observation-c1b-v1.md',
      'app/gateway/build.gradle.kts','app/gateway/src/debug/AndroidManifest.xml',
      'app/gateway/src/main/java/dev/magina/gateway/tablet/c1b/TabletC1bModel.kt','app/gateway/src/main/java/dev/magina/gateway/tablet/c1b/TabletC1bProbe.kt','app/gateway/src/main/java/dev/magina/gateway/tablet/c1b/AndroidTabletC1bSource.kt',
      'app/gateway/src/debug/java/dev/magina/gateway/tablet/c1b/TabletC1bContentProvider.kt','app/gateway/src/debug/java/dev/magina/gateway/tablet/c1b/TabletC1bProtocol.kt','app/gateway/src/debug/java/dev/magina/gateway/tablet/c1b/TabletC1bReadCoordinator.kt','app/gateway/src/debug/java/dev/magina/gateway/tablet/c1b/TabletC1bRuntimeController.kt','app/gateway/src/debug/java/dev/magina/gateway/tablet/c1b/TrustedRuntimeContextFactory.kt','app/gateway/src/debug/java/dev/magina/gateway/tablet/c1b/C1bPendingStartRegistry.kt')
    foreach($relative in $overlay){$from=Join-Path $SourceRoot ($relative-replace'/','\');$to=Join-Path $repo ($relative-replace'/','\');$parent=Split-Path $to -Parent;if(-not(Test-Path $parent)){[void](New-Item -ItemType Directory -Force $parent)};Copy-Item -LiteralPath $from -Destination $to -Force}
    $gradleScript=Join-Path $repo 'app\fake-gradle.ps1';[IO.File]::WriteAllText($gradleScript,@'
$ErrorActionPreference='Stop';$state=$env:TL1_C1B_E2E_STATE
[IO.File]::WriteAllText((Join-Path $state 'challenge.txt'),$env:TABLET_C1B_BUILD_CHALLENGE,[Text.UTF8Encoding]::new($false))
[IO.File]::WriteAllText((Join-Path $state 'build-head.txt'),$env:TL1_C1B_EXPECTED_COMMIT_SHA,[Text.UTF8Encoding]::new($false))
$apk=Join-Path $PSScriptRoot 'gateway\build\outputs\apk\debug\gateway-debug.apk';[void](New-Item -ItemType Directory -Force (Split-Path $apk -Parent));[IO.File]::WriteAllBytes($apk,[byte[]](1,3,3,7,9,2,6,8))
'@,[Text.UTF8Encoding]::new($false))
    $gradle=Join-Path $repo 'app\gradlew.bat';[IO.File]::WriteAllText($gradle,"@echo off`r`n`"$Pwsh`" -NoProfile -File `"$gradleScript`" %*`r`n",[Text.Encoding]::ASCII)
    $signer=Join-Path $sdk 'build-tools\99.0.0\apksigner.bat';[IO.File]::WriteAllText($signer,"@echo off`r`necho Signer #1 certificate SHA-256 digest: $('c'*64)`r`n",[Text.Encoding]::ASCII)
    Copy-Item -LiteralPath (Join-Path $SourceRoot 'scripts\tests\fixtures\tablet-layout-observation\c1b-v1\real-shape-topology-only.json') -Destination (Join-Path $state 'observation-template.json')
    $fakeSource=@'
using System;using System.IO;using System.Text;using System.Text.RegularExpressions;using System.Security.Cryptography;using System.Diagnostics;
public static class C1bFakeAdb {
 static string S(){return Environment.GetEnvironmentVariable("TL1_C1B_E2E_STATE");}
 static void Out(string v){Console.OutputEncoding=new UTF8Encoding(false);Console.Out.Write(v);}
 static string Read(string n){return File.ReadAllText(Path.Combine(S(),n),Encoding.UTF8).Trim();}
 static void Log(string[] a){File.AppendAllText(Path.Combine(S(),"adb.log"),string.Join("\u001f",a)+"\n",new UTF8Encoding(false));}
 static void ControlOut(string v){File.AppendAllText(Path.Combine(S(),"control-transcript.log"),v+"\n",new UTF8Encoding(false));Out(v);}
 static string Hash(byte[] b){using(var h=SHA256.Create())return "sha256:"+BitConverter.ToString(h.ComputeHash(b)).Replace("-","").ToLowerInvariant();}
 static string Control(string run,string state,long gen,int c1,int c2,string tokens,string flight,string reason){
  string commit=Read("commit.txt"),artifact=Read("artifact.txt"),challenge=Read("challenge.txt");bool ok=state=="ready_c1"||state=="capturing_c1"||state=="ready_c2"||state=="capturing_c2"||state=="complete";
  string next=state=="ready_c1"?"capture_c1":state=="ready_c2"?"capture_c2":state=="complete"?"read_result":(state.StartsWith("capturing")?"wait":"none");
  return "{\"schema\":\"tablet-c1b-control/v1\",\"ok\":"+(ok?"true":"false")+",\"run_id\":\""+run+"\",\"generation\":"+gen+",\"state\":\""+state+"\",\"next\":\""+next+"\",\"reason_code\":"+(reason==null?"null":"\""+reason+"\"")+",\"in_flight_token\":"+(flight==null?"null":"\""+flight+"\"")+",\"c1_requests_accepted\":"+c1+",\"c2_requests_accepted\":"+c2+",\"committed_tokens\":"+tokens+",\"recapture_count\":0,\"expected_title_hash\":\"sha256:5d3510ec998c991305fcede15b32be9ea1c4061d82ab15a3994a38faa243311c\",\"producer_commit_sha\":\""+commit+"\",\"producer_artifact_sha256\":\""+artifact+"\",\"provider\":{\"authority\":\"dev.magina.gateway.tablet.c1b\",\"protocol_version\":\"1\",\"package_name\":\"dev.magina.gateway\",\"version_name\":\"0.1.0-m1a\",\"version_code\":1,\"embedded_git_head\":\""+commit+"\",\"build_challenge\":\""+challenge+"\",\"a11y_service_ready\":true}}";
 }
 static string Absent(string run,string reason){string commit=Read("commit.txt"),artifact=Read("artifact.txt");return Control(run,"aborted",0,0,0,"[]",null,"session_aborted").Replace("\"state\":\"aborted\"","\"state\":\"absent\"").Replace("\"reason_code\":\"session_aborted\"","\"reason_code\":\""+reason+"\"").Replace("\"expected_title_hash\":\"sha256:5d3510ec998c991305fcede15b32be9ea1c4061d82ab15a3994a38faa243311c\"","\"expected_title_hash\":null").Replace("\"producer_commit_sha\":\""+commit+"\"","\"producer_commit_sha\":null").Replace("\"producer_artifact_sha256\":\""+artifact+"\"","\"producer_artifact_sha256\":null");}
 static string Observation(string run){byte[] t0=File.ReadAllBytes(Path.Combine(S(),"t0.bin"));string t0raw=Encoding.UTF8.GetString(t0);string t0at=Regex.Match(t0raw,"\\\"captured_at_utc\\\"\\s*:\\s*\\\"([^\\\"]+)\\\"").Groups[1].Value;DateTime now=DateTime.UtcNow;string c2=now.ToString("yyyy-MM-dd'T'HH:mm:ss.fffffff'Z'"),c1=now.AddSeconds(-1).ToString("yyyy-MM-dd'T'HH:mm:ss.fffffff'Z'");string x=File.ReadAllText(Path.Combine(S(),"observation-template.json"),Encoding.UTF8);
  x=x.Replace("tl1-c1b-fixture-real-shape",run).Replace("sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","sha256:5d3510ec998c991305fcede15b32be9ea1c4061d82ab15a3994a38faa243311c").Replace("\"offline_fixture\"","\"gateway_runtime_probe\"").Replace("\"source_kind\": \"gateway_runtime_probe\"","\"source_kind\": \"trusted_runtime\"").Replace("0000000000000000000000000000000000000000",Read("commit.txt")).Replace("sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",Read("artifact.txt")).Replace("sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",Hash(t0)).Replace("2026-08-26T00:00:00.0000000Z",t0at).Replace("2026-08-26T00:00:01.0000000Z",c1).Replace("2026-08-26T00:00:02.0000000Z",c2);return x;
 }
 public static int Main(string[] a){Console.OutputEncoding=new UTF8Encoding(false);Log(a);if(a.Length==1&&a[0]=="version"){Out("Android Debug Bridge version 1.0.41\r\nVersion 36.0.0-13206524\r\nInstalled as "+Process.GetCurrentProcess().MainModule.FileName+"\r\n");return 0;}if(a.Length==1&&a[0]=="devices"){Out("List of devices attached\r\nFAKE123\tdevice\r\n");return 0;}if(a.Length<3||a[0]!="-s"||a[1]!="FAKE123")return 90;
  string k=string.Join(" ",a,2,a.Length-2);if(k=="shell getprop ro.build.fingerprint"){Out("vivo/fixture/pa2553:16/BUILD/1:user/release-keys");return 0;}if(k=="shell cat /proc/sys/kernel/random/boot_id"){Out("01234567-89ab-cdef-0123-456789abcdef");return 0;}if(k=="shell settings get secure enabled_accessibility_services"){Out("dev.magina.gateway/dev.magina.gateway.a11y.GatewayA11yService");return 0;}if(k=="shell dumpsys accessibility"){Out("Bound services: dev.magina.gateway/dev.magina.gateway.a11y.GatewayA11yService");return 0;}if(a[2]=="install"){File.AppendAllText(Path.Combine(S(),"install.log"),"1\n");Out("Success");return 0;}if(k=="shell pm path dev.magina.gateway"){Out("package:/data/app/~~fixture/dev.magina.gateway-fixture/base.apk");return 0;}if(k=="shell dumpsys package dev.magina.gateway"){Out("versionCode=1 minSdk=30 targetSdk=36\nversionName=0.1.0-m1a");return 0;}if(a.Length==5&&a[2]=="exec-out"&&a[3]=="cat"){using(var o=Console.OpenStandardOutput())o.Write(File.ReadAllBytes(Path.Combine(S(),"apk.bin")),0,File.ReadAllBytes(Path.Combine(S(),"apk.bin")).Length);return 0;}
  if(a.Length==7&&a[3]=="content"){string uri=a[6].Trim('\'');string run=Regex.Match(uri,"/(?:t0|status|result|abort|capture/c1|capture/c2)/([^?]+)").Groups[1].Value;if(a[2]=="exec-in"){using(var m=new MemoryStream()){Console.OpenStandardInput().CopyTo(m);File.WriteAllBytes(Path.Combine(S(),"t0.bin"),m.ToArray());}File.WriteAllText(Path.Combine(S(),"run.txt"),run);File.WriteAllText(Path.Combine(S(),"commit.txt"),Regex.Match(uri,"producer_commit_sha=([0-9a-f]{40})").Groups[1].Value);File.WriteAllText(Path.Combine(S(),"artifact.txt"),Regex.Match(uri,"producer_artifact_sha256=(sha256:[0-9a-f]{64})").Groups[1].Value);return 0;}if(uri.Contains("/status/")){if(Environment.GetEnvironmentVariable("TL1_C1B_E2E_SCENARIO")=="tamper"&&File.Exists(Path.Combine(S(),"tamper-"+run+".txt"))){ControlOut(Control(run,"capturing_c1",7,0,0,"[]","c1",null));return 0;}ControlOut(Control(run,"ready_c1",7,0,0,"[]",null,null));return 0;}if(uri.Contains("/capture/c1/")){File.AppendAllText(Path.Combine(S(),"c1.log"),"1\n");if(Environment.GetEnvironmentVariable("TL1_C1B_E2E_SCENARIO")=="tamper"){File.WriteAllText(Path.Combine(S(),"tamper-"+run+".txt"),"1");ControlOut(Control(run,"capturing_c1",7,1,0,"[]","c1",null));return 0;}ControlOut(Control(run,"ready_c2",7,1,0,"[\"c1\"]",null,null));return 0;}if(uri.Contains("/capture/c2/")){File.AppendAllText(Path.Combine(S(),"c2.log"),"1\n");ControlOut(Control(run,"complete",7,1,1,"[\"c1\",\"c2\"]",null,null));return 0;}if(uri.Contains("/result/")){File.AppendAllText(Path.Combine(S(),"result.log"),"1\n");string scenario=Environment.GetEnvironmentVariable("TL1_C1B_E2E_SCENARIO");if(scenario=="result_control"||scenario=="malformed_abort"){Out(Control(run,"complete",7,1,1,"[\"c1\",\"c2\"]",null,null));return 0;}Out(Observation(run));return 0;}if(uri.Contains("/abort/")){File.AppendAllText(Path.Combine(S(),"abort.log"),"1\n");string scenario=Environment.GetEnvironmentVariable("TL1_C1B_E2E_SCENARIO");if(scenario=="result_control"){Out(Control(run,"expired",7,1,1,"[\"c1\",\"c2\"]",null,"session_expired"));return 0;}if(scenario=="malformed_abort"){Out(Absent(run,"t0_pending"));return 0;}if(scenario=="tamper"){Out(Control(run,"aborted",7,1,0,"[]",null,"session_aborted"));return 0;}Out(Control(run,"aborted",7,0,0,"[]",null,"session_aborted"));return 0;}}
  if(k=="shell getprop ro.product.brand"||k=="shell getprop ro.product.manufacturer"){Out("vivo");return 0;}if(k=="shell getprop ro.product.model"){Out("FixturePad");return 0;}if(k=="shell getprop ro.product.name"||k=="shell getprop ro.product.device"){Out("fixture_pad");return 0;}if(k=="shell getprop ro.build.version.release"){Out("16");return 0;}if(k=="shell getprop ro.build.version.sdk"){Out("36");return 0;}if(k=="shell getprop ro.product.cpu.abilist"){Out("arm64-v8a,armeabi-v7a");return 0;}if(k=="shell wm size"){Out("Physical size: 1600x2560");return 0;}if(k=="shell wm density"){Out("Physical density: 320");return 0;}if(k=="shell dumpsys activity activities"){Out("mGlobalConfiguration={1.0 zh_CN sw800dp w800dp h1200dp}\ntopResumedActivity=ActivityRecord{abc u0 com.tencent.mm/.ui.LauncherUI t10}");return 0;}if(k=="shell dumpsys window windows"){Out("WINDOW MANAGER WINDOWS\n mCurrentFocus=Window{abc u0 com.tencent.mm/.ui.LauncherUI}\n Window #0 Window{abc u0 com.tencent.mm/.ui.LauncherUI}:\n mDisplayId=0\n mAttrs={(0,0)(fillxfill) ty=BASE_APPLICATION}\n mFrame=[0,0][2560,1600]\n mWindowingMode=fullscreen\n isOnScreen=true");return 0;}if(k=="shell dumpsys display"){Out("Display 0: rotation=1");return 0;}if(k=="shell dumpsys power"){Out("mWakefulness=Awake");return 0;}if(k=="shell dumpsys window policy"){Out("mShowingLockscreen=false");return 0;}if(k=="shell settings get global zen_mode"){Out("0");return 0;}if(k=="shell settings get secure default_input_method"){Out("dev.magina.gateway/.ime.GatewayIme");return 0;}if(k=="shell dumpsys input_method"){Out("mInputShown=false\nmImeWindowVis=0x0");return 0;}if(k=="shell am get-config"){Out("config: zh-rCN-ldltr-sw800dp-w800dp-h1200dp-normal-long");return 0;}return 97;
 }
}
'@
    $fakeCs=Join-Path $root 'fake-adb.cs';$fakeExe=Join-Path $sdk 'platform-tools\adb.exe';[IO.File]::WriteAllText($fakeCs,$fakeSource,[Text.UTF8Encoding]::new($false));$csc=Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe';if(-not(Test-Path $csc)){$csc=Join-Path $env:WINDIR 'Microsoft.NET\Framework\v4.0.30319\csc.exe'};&$csc /nologo /target:exe "/out:$fakeExe" $fakeCs;if($LASTEXITCODE-ne0){throw 'E2E fake adb compile failed'}
    [void](Run-Git $repo @('config','user.email','c1b-e2e@invalid.local'));[void](Run-Git $repo @('config','user.name','C1b E2E'));[void](Run-Git $repo @('add','-f','--','.'));[void](Run-Git $repo @('commit','-q','-m','c1b e2e synthetic clean head'));$head=(Run-Git $repo @('rev-parse','HEAD')).Trim()
    $apkFixture=[byte[]](1,3,3,7,9,2,6,8);[IO.File]::WriteAllBytes((Join-Path $state 'apk.bin'),$apkFixture)
    $environment=@{TL1_C1B_E2E_STATE=$state;ANDROID_HOME=$sdk;ANDROID_SDK_ROOT=$sdk;TL1_C1B_E2E_SCENARIO='success'}
    $runner=Join-Path $repo 'scripts\run-tablet-layout-c1b.ps1';$outsideAdb=Join-Path $root 'arbitrary-adb.exe';Copy-Item -LiteralPath $fakeExe -Destination $outsideAdb
    $outside=Invoke-TL1C1aProcess -FilePath $Pwsh -Arguments @('-NoProfile','-File',$runner,'-AdbPath',$outsideAdb,'-ExpectedCommitSha',$head,'-Provision') -Operation 'C1b actual runner rejects non-SDK adb E2E' -Environment $environment -TimeoutSec 30 -AllowFailure;Check ($outside.ExitCode-ne0) 'runner accepted arbitrary executable outside SDK';Check (-not(Test-Path (Join-Path $state 'install.log'))) 'non-SDK adb rejection reached install'
    $success=Invoke-TL1C1aProcess -FilePath $Pwsh -Arguments @('-NoProfile','-File',$runner,'-AdbPath',$fakeExe,'-ExpectedCommitSha',$head,'-Provision') -Operation 'C1b actual runner fake-ADB success E2E' -Environment $environment -TimeoutSec 180 -AllowFailure
    if($success.ExitCode-ne0){throw "success runner exit=$($success.ExitCode) stdout=$($success.Text) stderr=$($success.Stderr)"}
    $runDirs=@(Get-ChildItem (Join-Path $repo 'docs\runs\evidence') -Directory|Where-Object Name -like 'tl1-c1b-*');Check ($runDirs.Count-eq1) 'success E2E run dir count';$successDir=Join-Path $runDirs[0].FullName 'tablet-layout-c1b';$sidecarPath=Join-Path $successDir 'tablet-layout-c1b-sidecar-v1.json';Check (Test-Path $sidecarPath) 'success sidecar missing'
    foreach($name in @('upstream-t0-v5.json','tablet-layout-observation-c1b-v1.json','tablet-layout-observation-validation-c1b-v1.json','tablet-layout-c1b-sidecar-v1.json')){Check (Test-Path (Join-Path $successDir $name)) "success artifact missing $name"};Check (Test-Path (Join-Path $runDirs[0].FullName 'tablet-profile.json')) 'fresh T0 original missing'
    $sidecar=Get-Content $sidecarPath -Raw|ConvertFrom-Json -DateKind String;Assert-TL1C1bSidecarCrossBindings $sidecar;Check ((Get-Content $sidecarPath -Raw)|Test-Json -SchemaFile (Join-Path $repo 'docs\contracts\tablet-layout-c1b-sidecar-v1.schema.json')) 'success sidecar schema';Check ($sidecar.capture.status_poll_count-eq1) 'status count'
    $adbLines=[IO.File]::ReadAllLines((Join-Path $state 'adb.log'),[Text.UTF8Encoding]::new($false));$execInLines=@($adbLines|Where-Object{$_-cmatch("^-s$([char]0x1f)FAKE123$([char]0x1f)exec-in$([char]0x1f)content$([char]0x1f)write$([char]0x1f)--uri$([char]0x1f)")});Check ($execInLines.Count-eq1) 'T0 exec-in count success'
    $originalT0=Join-Path $runDirs[0].FullName 'tablet-profile.json';$forwardedT0=Join-Path $state 't0.bin';$originalBytes=[IO.File]::ReadAllBytes($originalT0);$forwardedBytes=[IO.File]::ReadAllBytes($forwardedT0);try{Check ([Convert]::ToHexString($originalBytes)-ceq[Convert]::ToHexString($forwardedBytes)) 'T0 exec-in stdin bytes drift'}finally{if($originalBytes.Length){[Array]::Clear($originalBytes,0,$originalBytes.Length)};if($forwardedBytes.Length){[Array]::Clear($forwardedBytes,0,$forwardedBytes.Length)}}
    $transcriptLines=[IO.File]::ReadAllLines((Join-Path $state 'control-transcript.log'),[Text.UTF8Encoding]::new($false));$transcriptBytes=[Text.UTF8Encoding]::new($false).GetBytes($transcriptLines-join"`n");try{$independentTranscriptSha=Get-IndependentSha256 $transcriptBytes}finally{if($transcriptBytes.Length){[Array]::Clear($transcriptBytes,0,$transcriptBytes.Length)}};Check ($sidecar.provider.control_transcript_sha256-ceq$independentTranscriptSha) 'control transcript independent hash mismatch'
    foreach($artifactName in @('upstream_t0','observation','validation')){$artifact=$sidecar.artifacts.$artifactName;$artifactPath=Join-Path $successDir $artifact.relative_path;Check ((Get-IndependentFileSha256 $artifactPath)-ceq$artifact.sha256) "artifact independent hash mismatch: $artifactName"}
    Check ((Get-IndependentFileSha256 $fakeExe)-ceq$sidecar.transport.executable_sha256_before-and$sidecar.transport.executable_sha256_before-ceq$sidecar.transport.executable_sha256_after) 'adb executable independent hash mismatch';Check ($sidecar.transport.trust_root-ceq'android_sdk_platform_tools'-and$sidecar.transport.canonical_relative_path-ceq'platform-tools/adb.exe'-and$sidecar.transport.installed_as_canonical) 'adb canonical trust binding missing'
    Check (@(Get-Content (Join-Path $state 'install.log')).Count-eq1) 'install count success';Check (@(Get-Content (Join-Path $state 'c1.log')).Count-eq1) 'c1 count success';Check (@(Get-Content (Join-Path $state 'c2.log')).Count-eq1) 'c2 count success';Check (@(Get-Content (Join-Path $state 'result.log')).Count-eq1) 'result count success';Check (-not(Test-Path (Join-Path $state 'abort.log'))) 'abort occurred on success'

    $knownRuns=@($runDirs.FullName);$beforeResultC1=@(Get-Content (Join-Path $state 'c1.log')).Count;$beforeResultC2=@(Get-Content (Join-Path $state 'c2.log')).Count;$beforeResultReads=@(Get-Content (Join-Path $state 'result.log')).Count;$environment.TL1_C1B_E2E_SCENARIO='result_control';$resultControl=Invoke-TL1C1aProcess -FilePath $Pwsh -Arguments @('-NoProfile','-File',$runner,'-AdbPath',$fakeExe,'-ExpectedCommitSha',$head,'-Provision') -Operation 'C1b actual runner fake-ADB result-control E2E' -Environment $environment -TimeoutSec 180 -AllowFailure;Check ($resultControl.ExitCode-ne0) 'result control runner succeeded'
    $afterResult=@(Get-ChildItem (Join-Path $repo 'docs\runs\evidence') -Directory|Where-Object Name -like 'tl1-c1b-*');Check ($afterResult.Count-eq$knownRuns.Count+1) 'result control run dir missing';$resultFailureRoot=($afterResult|Where-Object{$knownRuns-cnotcontains$_.FullName})[0].FullName;$resultFailureDir=Join-Path $resultFailureRoot 'tablet-layout-c1b';$resultFailurePath=Join-Path $resultFailureDir 'tablet-layout-c1b-failure.json';Check (Test-Path $resultFailurePath) 'result control failure evidence missing';$resultFailure=Read-FailureEvidenceStrict $resultFailurePath;Check ($resultFailure.status-ceq'failed'-and$resultFailure.cleanup-ceq'completed'-and-not$resultFailure.runtime_origin_verified-and-not$resultFailure.runtime_evidence) 'result control failure evidence/cleanup drift';Check (-not(Test-Path (Join-Path $resultFailureDir 'tablet-layout-c1b-sidecar-v1.json'))) 'result control forged success sidecar';Check (@(Get-Content (Join-Path $state 'c1.log')).Count-eq$beforeResultC1+1) 'result control c1 count';Check (@(Get-Content (Join-Path $state 'c2.log')).Count-eq$beforeResultC2+1) 'result control c2 count';Check (@(Get-Content (Join-Path $state 'result.log')).Count-eq$beforeResultReads+1) 'result control result count';Check (@(Get-Content (Join-Path $state 'abort.log')).Count-eq1) 'result control abort count'

    $knownRuns=@($afterResult.FullName);$beforeMalformedAborts=@(Get-Content (Join-Path $state 'abort.log')).Count;$environment.TL1_C1B_E2E_SCENARIO='malformed_abort';$malformedAbort=Invoke-TL1C1aProcess -FilePath $Pwsh -Arguments @('-NoProfile','-File',$runner,'-AdbPath',$fakeExe,'-ExpectedCommitSha',$head,'-Provision') -Operation 'C1b actual runner fake-ADB malformed-abort E2E' -Environment $environment -TimeoutSec 180 -AllowFailure;Check ($malformedAbort.ExitCode-ne0) 'malformed abort runner succeeded'
    $afterMalformed=@(Get-ChildItem (Join-Path $repo 'docs\runs\evidence') -Directory|Where-Object Name -like 'tl1-c1b-*');Check ($afterMalformed.Count-eq$knownRuns.Count+1) 'malformed abort run dir missing';$malformedFailureDir=Join-Path (($afterMalformed|Where-Object{$knownRuns-cnotcontains$_.FullName})[0].FullName) 'tablet-layout-c1b';$malformedFailure=Read-FailureEvidenceStrict (Join-Path $malformedFailureDir 'tablet-layout-c1b-failure.json');Check ($malformedFailure.status-ceq'failed'-and$malformedFailure.cleanup-ceq'failed'-and-not$malformedFailure.runtime_origin_verified-and-not$malformedFailure.runtime_evidence) 'malformed abort did not fail closed';Check (-not(Test-Path (Join-Path $malformedFailureDir 'tablet-layout-c1b-sidecar-v1.json'))) 'malformed abort forged success sidecar';Check (@(Get-Content (Join-Path $state 'abort.log')).Count-eq$beforeMalformedAborts+1) 'malformed abort attempt count'

    $knownRuns=@($afterMalformed.FullName);$beforeC1=@(Get-Content (Join-Path $state 'c1.log')).Count;$beforeC2=@(Get-Content (Join-Path $state 'c2.log')).Count;$beforeResults=@(Get-Content (Join-Path $state 'result.log')).Count;$beforeAborts=@(Get-Content (Join-Path $state 'abort.log')).Count;$environment.TL1_C1B_E2E_SCENARIO='tamper';$tamper=Invoke-TL1C1aProcess -FilePath $Pwsh -Arguments @('-NoProfile','-File',$runner,'-AdbPath',$fakeExe,'-ExpectedCommitSha',$head,'-Provision') -Operation 'C1b actual runner fake-ADB status-tuple tamper E2E' -Environment $environment -TimeoutSec 180 -AllowFailure;Check ($tamper.ExitCode-ne0) 'tampered intermediate status tuple runner succeeded'
    $after=@(Get-ChildItem (Join-Path $repo 'docs\runs\evidence') -Directory|Where-Object Name -like 'tl1-c1b-*');Check ($after.Count-eq$knownRuns.Count+1) 'tamper run dir missing';$failureDir=Join-Path (($after|Where-Object{$knownRuns-cnotcontains$_.FullName})[0].FullName) 'tablet-layout-c1b';$failurePath=Join-Path $failureDir 'tablet-layout-c1b-failure.json';Check (Test-Path $failurePath) 'failure evidence missing';$failure=Read-FailureEvidenceStrict $failurePath;Check ($failure.status-ceq'failed'-and$failure.cleanup-ceq'completed'-and-not$failure.runtime_origin_verified-and-not$failure.runtime_evidence) 'tamper failure evidence/cleanup drift';Check (-not(Test-Path (Join-Path $failureDir 'tablet-layout-c1b-sidecar-v1.json'))) 'tamper forged success sidecar';Check (@(Get-Content (Join-Path $state 'c1.log')).Count-eq$beforeC1+1) 'tamper c1 count';Check (@(Get-Content (Join-Path $state 'c2.log')).Count-eq$beforeC2) 'tamper reached c2';Check (@(Get-Content (Join-Path $state 'result.log')).Count-eq$beforeResults) 'tamper reached result';Check (@(Get-Content (Join-Path $state 'abort.log')).Count-eq$beforeAborts+1) 'tamper abort count'
    [pscustomobject]@{schema='tablet-layout-c1b-host-e2e/v1';status='passed';fake_adb=$true;coverage=@('runner_e2e_success','runner_e2e_result_control_abort','runner_e2e_malformed_abort_fail_closed','runner_e2e_tamper_abort')}|ConvertTo-Json -Compress
}finally{if($env:TL1_C1B_KEEP_E2E_TEMP-ceq'1'){[Console]::Error.WriteLine("C1b E2E temp kept: $root")}else{Remove-Item -LiteralPath $root -Recurse -Force -ErrorAction SilentlyContinue}}
